version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ${NGINX_HOST}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./deployments/volumes/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - api
    env_file:
      - config/app.env
    networks:
      - pottogether-net

  api: 
    image: ${API_IMAGE}
    container_name: ${API_HOST}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./deployments/volumes/api:/app/cmd/api
    env_file:
      - config/app.env
    networks:
      - pottogether-net

networks:
  pottogether-net:
    driver: bridge